liste_filieres=["PC","MP","PSI","PT","BCPST"]
liste_banques=["Concours Polytechnique - ENS",
"Concours Mines-Telecom",
"Concours Mines-Ponts",
"Arts Et Métiers",
"Concours Centrale-Supélec",
"Concours CCINP",
"Autres","Agro Veto","G2E","PAS DE VOEUX"]

dico_banques={"ECOLE POLYTECHNIQUE":"Concours Polytechnique - ENS",
              "ENS Paris-Saclay":"Concours Polytechnique - ENS",
              "ENS Ulm":"Concours Polytechnique - ENS",
              "ESPCI Paris":"Concours Polytechnique - ENS",
              "ENS de Lyon":"Concours Polytechnique - ENS",
              "ECOLE POLYTECHNIQUE":"Concours Polytechnique - ENS",
              "ENS Paris-Saclay":"Concours Polytechnique - ENS",
              "ENS Ulm":"Concours Polytechnique - ENS",
              "ESPCI Paris":"Concours Polytechnique - ENS",
              "ENS de Lyon":"Concours Polytechnique - ENS",
              "ENSTA Bretagne (filière sous statut étudiant)":"Concours Mines-Telecom",
              "ENSTA Bretagne (filière sous statut IETA - Direction Générale de l'Armement)":"Concours Mines-Telecom",
              "IMT Atlantique":"Concours Mines-Telecom",
              "Mines Saint Etienne-ISMIN":"Concours Mines-Telecom",
              "TELECOM SudParis":"Concours Mines-Telecom",
              "Institut Mines-Télécom Business School (IMT-BS)":"Concours Mines-Telecom",
              "IMT Mines Alès":"Concours Mines-Telecom",
              "IMT Mines Albi":"Concours Mines-Telecom",
              "IMT Nord Europe en partenariat avec Polyvia Formation":"Concours Mines-Telecom",
              "TELECOM St Etienne":"Concours Mines-Telecom",
              "ENSSAT Lannion":"Concours Mines-Telecom",
              "ENTPE Lyon Fonctionnaire":"Concours Mines-Telecom",
              "ENTPE Lyon Civil":"Concours Mines-Telecom",
              "TELECOM PHYSIQUE Strasbourg":"Concours Mines-Telecom",
              "EURECOM":"Concours Mines-Telecom",
              "Télécom Physique Strasbourg Informatique et Réseaux":"Concours Mines-Telecom",
              "ENSIIE Evry OUI MAIS":"Concours Mines-Telecom",
              "IMT Nord Europe":"Concours Mines-Telecom",
              "TELECOM Nancy":"Concours Mines-Telecom",
              "TELECOM St Etienne - Statut étudiant":"Concours Mines-Telecom",
              "MINES Paris":"Concours Mines-Ponts",
              "ENSTA Paris":"Concours Mines-Ponts",
              "ENSAE Paris":"Concours Mines-Ponts",
              "PONTS ParisTech":"Concours Mines-Ponts",
              "ENSTA Paris - apprentissage":"Concours Mines-Ponts",
              "MINES de NANCY":"Concours Mines-Ponts",
              "MINES SAINT-ETIENNE":"Concours Mines-Ponts",
              "ISAE - SUPAERO Toulouse":"Concours Mines-Ponts",
              "Chimie ParisTech":"Concours Mines-Ponts",
              "IMT Atlantique":"Concours Mines-Ponts",
              "MINES SAINTETIENNE":"Concours Mines-Ponts",
              "TELECOM Paris":"Concours Mines-Ponts",
              "Arts et Métiers":"Arts Et Métiers",
              "Arts et Métiers - ingénieurs militaires":"Arts Et Métiers",
              "Centrale Nantes":"Concours Centrale-Supélec",
              "CentraleSupélec - cursus apprenti - Campus Metz":"Concours Centrale-Supélec",
              "CentraleSupélec - statut étudiant":"Concours Centrale-Supélec",
              "ESTP - campus de Cachan":"Concours Centrale-Supélec",
              "Institut d'optique Graduate School (SupOptique)":"Concours Centrale-Supélec",
              "ESTP - campus de Dijon":"Concours Centrale-Supélec",
              "ESTP - campus de Cachan":"Concours Centrale-Supélec",
              "CentraleSupélec - statut étudiant":"Concours Centrale-Supélec",
              "Centrale Nantes":"Concours Centrale-Supélec",
              "Centrale Méditerranée":"Concours Centrale-Supélec",
              "Centrale Lyon":"Concours Centrale-Supélec",
              "Centrale Lille":"Concours Centrale-Supélec",
              "ESTP - campus de Troyes":"Concours Centrale-Supélec",
              "ENSEA Cergy":"Concours Centrale-Supélec",
              "CentraleSupélec - cursus apprenti - Campus Rennes":"Concours Centrale-Supélec",
              "EPF campus Montpellier":"Concours Centrale-Supélec",
              "ENSAI Rennes Civil":"Concours CCINP",
              "Toulouse INP - ENSIACET - Chimie":"Concours CCINP",
              "SUPMICROTECH ENSMM Besançon":"Concours CCINP",
              "Clermont Auvergne INP - SIGMA - mécanique":"Concours CCINP",
              "Grenoble INP - ENSE3":"Concours CCINP",
              "Grenoble INP - ENSIMAG":"Concours CCINP",
              "Grenoble INP - Phelma (Physique Electronique Télécoms)":"Concours CCINP",
              "Grenoble INP - Phelma (Physique Matériaux Procédés)":"Concours CCINP",
              "ISAE-ENSMA Poitiers":"Concours CCINP",
              "Lorraine INP - ENSEM - Energie":"Concours CCINP",
              "Toulouse INP - ENSIACET - Génie Industriel":"Concours CCINP",
              "Toulouse INP - ENSEEIHT - Mécanique des Fluides-Energetique-Environnement (MFEE)":"Concours CCINP",
              "Toulouse INP - ENSEEIHT - Electronique-Energie-Automatique (EEA)":"Concours CCINP",
              "ISAE-Supméca Paris":"Concours CCINP",
              "ESM Saint-Cyr":"Concours CCINP",
              "ENTPE Lyon Fonctionnaire":"Concours CCINP",
              "ENSICAEN Génie Physique et systèmes Embarqués":"Concours CCINP",
              "Clermont Auverge INP - SIGMA Clermont\xa0 Mécanique Avancée":"Concours CCINP",
              "ENAC Toulouse Civil":"Concours CCINP",
              "ENAC Toulouse - Contrôleurs aériens":"Concours CCINP",
              "ECOLE DE L'AIR Pilote":"Concours CCINP",
              "Bordeaux INP - ENSC Cognitique":"Concours CCINP",
              "Clermont Auvergne INP - SIGMA - chimie":"Concours CCINP",
              "CPE LYON Chimie – génie des procédés":"Concours CCINP",
              "CY TECH Cergy - Biotechnololgie":"Concours CCINP",
              "CY TECH Cergy-Pau - Informatique":"Concours CCINP",
              "Bordeaux INP - ENSMAC (ex ENSCBP) Chimie-Génie physique":"Concours CCINP",
              "ECPM Strasbourg":"Concours CCINP",
              "ENAC Toulouse Fonctionnaire":"Concours CCINP",
              "ENGEES Strasbourg Civil (étudiant)":"Concours CCINP",
              "ENSC Lille":"Concours CCINP",
              "ENSC Montpellier":"Concours CCINP",
              "ENSICAEN Mat. et Chimie":"Concours CCINP",
              "Bordeaux INP - ENSPIMA":"Concours CCINP",
              "Grenoble INP - Pagora":"Concours CCINP",
              "Lorraine INP - ENSIC":"Concours CCINP",
              "Toulouse INP - ENSIACET - Génie des Procédés":"Concours CCINP",
              "Bordeaux INP - ENSEIRB-MATMECA Informatique":"Concours CCINP",
              "Bordeaux INP - ENSEIRB-MATMECA Télecom.":"Concours CCINP",
              "SeaTech Toulon":"Concours CCINP",
              "ENSIIE Evry":"Concours CCINP",
              "ESTP - campus de Dijon":"Concours CCINP",
              "IMT Atlantique":"Concours CCINP",
              "Polytech Montpellier - Informatique et Gestion":"Concours CCINP",
              "Toulouse INP - ENSEEIHT - Sciences du Numérique":"Concours CCINP",
              "Grenoble INP - Esisar":"Concours CCINP",
              "Toulouse INP - ENSIACET - Génie chimique":"Concours CCINP",
              "Toulouse INP - ENSIACET - Matériaux":"Concours CCINP",
              "Bordeaux INP - ENSEIRB-MATMECA Electronique":"Concours CCINP",
              "CY TECH Cergy-Pau - Mathématiques":"Concours CCINP",
              "Lorraine INP - ENSEM - Spécialité des systèmes numériques":"Concours CCINP",
              "ESIEE Paris":"Concours CCINP",
              "ECAM LaSalle":"Autres",
              "ENSAIT Roubaix":"Autres",
              "ENSISA Mulhouse Mécanique":"Autres",
              "INSA Lyon Génie Civil et Urbanisme":"Autres",
              "INSA Lyon Génie Electrique":"Autres",
              "INSA Lyon Génie Industriel":"Autres",
              "INSA Lyon Génie Mécanique":"Autres",
              "INSA Lyon Informatique":"Autres",
              "INSA Lyon Biotechnologies et Bioinformatique":"Autres",
              "INSA Strasbourg Génie Thermique, Energétique et Environnement":"Autres",
              "INSA Strasbourg Génie Mécanique":"Autres",
              "INSA Hauts de France Mécatronique":"Autres",
              "INSA Hauts-de-France Audiovisuel et Multimédia":"Autres",
              "Toulouse INP - ENIT":"Autres",
              "CPE Lyon - apprentissage - Physique et Systèmes Microélectronique":"Autres",
              "ECOLE DE L'AIR Base":"Autres",
              "ECOLE NAVALE Brest":"Autres",
              "Polytech Orléans - Innovation en Conception et Matériaux":"Autres",
              "Polytech Grenoble Gestion des Risques":"Autres",
              "Polytech Clermont-Ferrand - Génie Civil":"Autres",
              "Polytech Lyon - Systèmes industriels, Robotique":"Autres",
              "Polytech Lyon - Informatique":"Autres",
              "Polytech Marseille - Mécanique, Energétique":"Autres",
              "Polytech Montpellier - Matériaux":"Autres",
              "Polytech Grenoble - Géotechnique et génie civil":"Autres",
              "Lorraine INP - ENSGSI":"Autres",
              "IPSA Paris":"Autres",
              "INSA Toulouse Automatique et Electronique":"Autres",
              "INSA Strasbourg Topographie":"Autres",
              "Grenoble INP - Génie industriel":"Autres",
              "ESTP - campus de Cachan":"Autres",
              "ESTIA Bidart":"Autres",
              "ESTACA Paris-Saclay : Aéronautique":"Autres",
              "ESTACA Bordeaux Aéronautique":"Autres",
              "ESTACA Paris-Saclay : Spatial":"Autres",
              "ESTACA Laval Automobile":"Autres",
              "ENSC Mulhouse":"Autres",
              "ESILV Paris-La Défense":"Autres",
              "EPITA campus Lyon":"Autres",
              "ECAM Rennes":"Autres",
              "ECOLE DE L'AIR Pilote":"Autres",
              "ENSIIE Evry":"Autres",
              "EPF campus Cachan":"Autres",
              "ESCOM Chimie Compiègne":"Autres",
              "ISAT Nevers - Infrastructures et Réseaux de Transports":"Autres",
              "ITECH Lyon":"Autres",
              "INSA Lyon Matériaux":"Autres",
              "INSA Lyon Télécommunications":"Autres",
              "INSA Hauts de France Génie Industriel":"Autres",
              "INSA Lyon Génie Energétique et Génie de l'Environnement":"Autres",
              "INSA Rouen Normandie Génie Energétique (Parcours énergétique et propulsion)":"Autres",
              "INSA Rennes Génie Civil et Urbain":"Autres",
              "INSA Lyon Génie Civil et Génie Urbain":"Autres",
              "INSA Rouen Normandie Mécanique":"Autres",
              "Magistère de Maths Grenoble":"Autres",
              "Polytech Sorbonne - Agroalimentaire":"Agro Veto",
              "Polytech Marseille - Génie Biologique, Biotechnologie":"Agro Veto",
              "ENSAIA":"Agro Veto",
              "VetAgro Sup":"Agro Veto",
              "Oniris VetAgroBio Nantes (École nationale vétérinaire de Nantes)":"Agro Veto",
              "Polytech Nice-Sophia - Génie biologique":"Agro Veto",
              "L'Institut Agro - Dijon (cursus ingénieur, en alimentation durable)":"Agro Veto",
              "L'Institut Agro - Dijon (cursus ingénieur, spécialités agronomie civil)":"Agro Veto",
              "Polytech Clermont - Génie Biologique":"Agro Veto",
              "Lorraine INP - ENSIC":"Agro Veto",
              "ECPM - ESBS Strasbourg - CHEMBIOTECH":"Agro Veto",
              "L'Institut Agro Rennes - Angers (cursus ingénieur, spécialités Horticulture et Paysage)":"Agro Veto",
              "Lorraine INP - ENSTIB":"Agro Veto",
              "ISIFC Besançon - Génie Biomédical":"Agro Veto",
              "ENSG Nancy":"G2E",
              "xxx":"Autres",
              "L3":"Autres",
              "5/2":"Autres",
              "PAS DE VOEUX":"PAS DE VOEUX"}

dico_compte={}
for f in liste_filieres :
    for b in liste_banques :
        dico_compte[(f,b)]=0

